"""create table usuario_vehiculo

Revision ID: 0ac767af2573
Revises: 9e815365ce79
Create Date: 2026-03-24 16:18:49.369818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac767af2573'
down_revision: Union[str, Sequence[str], None] = '9e815365ce79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_vehiculo',
    sa.Column('pfk_usuario', sa.BigInteger(), nullable=False),
    sa.Column('pfk_vehiculo', sa.String(length=6), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('kilometros_registro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pfk_usuario'], ['usuario.documento_identidad'], ),
    sa.ForeignKeyConstraint(['pfk_vehiculo'], ['vehiculo.placa'], ),
    sa.PrimaryKeyConstraint('pfk_usuario', 'pfk_vehiculo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_vehiculo')
    # ### end Alembic commands ###
